//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TA_DoctorEntities1 : DbContext
    {
        public TA_DoctorEntities1()
            : base("name=TA_DoctorEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adm_Offs> Adm_Offs { get; set; }
        public virtual DbSet<AdvRea> AdvRea { get; set; }
        public virtual DbSet<Audit> Audit { get; set; }
        public virtual DbSet<AvaDate> AvaDate { get; set; }
        public virtual DbSet<BodyParts> BodyParts { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Contrain> Contrain { get; set; }
        public virtual DbSet<District> District { get; set; }
        public virtual DbSet<DrugDuc> DrugDuc { get; set; }
        public virtual DbSet<HosDoctors> HosDoctors { get; set; }
        public virtual DbSet<HosEquipments> HosEquipments { get; set; }
        public virtual DbSet<Hospitals> Hospitals { get; set; }
        public virtual DbSet<illness> illness { get; set; }
        public virtual DbSet<InterRecord> InterRecord { get; set; }
        public virtual DbSet<MatNeetAt> MatNeetAt { get; set; }
        public virtual DbSet<Medicines> Medicines { get; set; }
        public virtual DbSet<MedRecordes> MedRecordes { get; set; }
        public virtual DbSet<MedType> MedType { get; set; }
        public virtual DbSet<OutPatientDep> OutPatientDep { get; set; }
        public virtual DbSet<Patients> Patients { get; set; }
        public virtual DbSet<ProQualif> ProQualif { get; set; }
        public virtual DbSet<Province> Province { get; set; }
        public virtual DbSet<SpeSite> SpeSite { get; set; }
        public virtual DbSet<SymDes> SymDes { get; set; }
        public virtual DbSet<Symptom> Symptom { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserCrowd> UserCrowd { get; set; }
        public virtual DbSet<VisitTime> VisitTime { get; set; }
    }
}
