//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrugDuc
    {
        public int DrID { get; set; }
        public int MID { get; set; }
        public string M_OrienSym { get; set; }
        public string M_Usage { get; set; }
        public string M_Sperci { get; set; }
        public string M_Depot { get; set; }
        public string M_Manuf { get; set; }
        public string M_Photos { get; set; }
        public string M_Remark { get; set; }
    
        public virtual Medicines Medicines { get; set; }
    }
}
