//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HosDoctors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HosDoctors()
        {
            this.Audit = new HashSet<Audit>();
            this.MedRecordes = new HashSet<MedRecordes>();
            this.ProQualif = new HashSet<ProQualif>();
            this.VisitTime = new HashSet<VisitTime>();
        }
    
        public int HDID { get; set; }
        public int AOID { get; set; }
        public string HD_Name { get; set; }
        public int HD_Sex { get; set; }
        public string HD_Phone { get; set; }
        public string HD_Photo { get; set; }
        public int HD_Age { get; set; }
        public string HD_Remark { get; set; }
        public decimal HD_Money { get; set; }
        public int HD_WorkYears { get; set; }
        public int HD_VisitNum { get; set; }
    
        public virtual Adm_Offs Adm_Offs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Audit> Audit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedRecordes> MedRecordes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProQualif> ProQualif { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitTime> VisitTime { get; set; }
    }
}
