//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedRecordes
    {
        public int MRID { get; set; }
        public int PID { get; set; }
        public int HID { get; set; }
        public int AOID { get; set; }
        public int HDID { get; set; }
        public System.DateTime MR_Time { get; set; }
        public string MR_Remark { get; set; }
    
        public virtual Adm_Offs Adm_Offs { get; set; }
        public virtual HosDoctors HosDoctors { get; set; }
        public virtual Hospitals Hospitals { get; set; }
        public virtual Patients Patients { get; set; }
    }
}
